//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PollWebApi.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class PollDataBaseEntities : DbContext
    {
        public PollDataBaseEntities()
            : base("name=PollDataBaseEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Options> Options { get; set; }
        public virtual DbSet<Poll> Poll { get; set; }
        public virtual DbSet<Views> Views { get; set; }
        public virtual DbSet<Votes> Votes { get; set; }
    }
}
